### ISSUE TITLE
Infeasable problem.Using previous control input

### ISSUE THREAD

**Issue by sparshgarg23** [matssteinweg/Multi-Purpose-MPC#3]
Hi,
thanks for updating the code,I ran it and saw that the message mentioned in the title is printed on the console.
After inspecitng the MPC.py it is my assumption that we set the current state and the spatial state and then try to solve the optimization problem.
So is this error generated by QSQP,and what do you think could be the reasons for it.
I will also try to search for it on my own

**Comment by matssteinweg** [comment]
Hi, 

that’s not really an error. From time to time it happens that the MPC problem becomes infeasible due to state and input constraints. In this case we just use the control signal computed in the previous iteration. We print the message just to see how often this occurs. It’s not really problematic if it only happens occasionally. Ideally, feasibility should be ensured in all situations. 

I hope this helps.

Best, Mats
